package com.aegis.event;

public enum SecurityEventType {
    HTTP_REQUEST,
    HTTP_RESPONSE,
    NETWORK_CONNECTION,
    AUTHENTICATION_EVENT,
    SUSPICIOUS_REQUEST,
    VULNERABILITY_INTERACTION
}
