package com.globalshield.retest.entity;

public enum RetestCheckType {
    HTTP_RESPONSE_VALIDATION,
    HEADER_VALIDATION,
    COOKIE_VALIDATION,
    TLS_CONFIGURATION_VALIDATION,
    ENDPOINT_REACHABILITY_VALIDATION,
    VULNERABILITY_RESCAN,
    ZAP_ALERT_REVALIDATION,
    NUCLEI_REVALIDATION,
    CONFIGURATION_REVALIDATION
}
