package com.aegis.assessment;

public enum AssessmentStage {
    TARGET_VALIDATION,
    DNS_DISCOVERY,
    PORT_DISCOVERY,
    TECHNOLOGY_DISCOVERY,
    HTTP_SECURITY_ANALYSIS,
    WEB_SERVER_ASSESSMENT,
    VULNERABILITY_ASSESSMENT,
    RESULT_NORMALIZATION,
    FINALIZATION
}
