package com.aegis.report.entity;

public enum ReportType {
    EXECUTIVE_SECURITY_REPORT,
    TECHNICAL_SECURITY_REPORT,
    VULNERABILITY_REPORT,
    ASSESSMENT_REPORT,
    INCIDENT_REPORT,
    FORENSIC_REPORT,
    DEFENSE_VALIDATION_REPORT,
    SECURITY_POSTURE_REPORT,
    REGRESSION_REPORT,
    MONITORING_REPORT
}
