package com.globalshield.forensics.enums;

public enum AttackStage {
    RECONNAISSANCE,
    DISCOVERY,
    INITIAL_ACCESS,
    VULNERABILITY_INTERACTION,
    AUTHENTICATION_ACTIVITY,
    SUSPICIOUS_REQUEST,
    POSSIBLE_EXPLOITATION,
    IMPACT,
    POSSIBLE_EXFILTRATION
}
