package com.aegis.audit;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    TARGET_CREATED,
    TARGET_UPDATED,
    TARGET_DISABLED,
    TARGET_ARCHIVED,
    AUTHORIZATION_CREATED,
    AUTHORIZATION_UPDATED,
    ASSESSMENT_CREATED,
    ASSESSMENT_START_REQUESTED,
    ASSESSMENT_STARTED,
    TOOL_EXECUTION_STARTED,
    TOOL_EXECUTION_COMPLETED,
    TOOL_EXECUTION_FAILED,
    ASSESSMENT_COMPLETED,
    ASSESSMENT_PARTIALLY_COMPLETED,
    ASSESSMENT_FAILED,
    ASSESSMENT_CANCELLED
}
